apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
      default: .
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
  workspaces:
    - name: source
    - name: dockerconfig
      optional: true
  results:
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.9.1
      workingDir: /workspace/source
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --digest-file=$(results.IMAGE_DIGEST.path)
      volumeMounts:
        - name: dockerconfig
          mountPath: /kaniko/.docker
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    - name: write-url
      image: bash:5.1.4
      script: |
        #!/usr/bin/env bash
        set -e
        echo -n "$(params.IMAGE)" | tee "$(results.IMAGE_URL.path)"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
